### ISSUE TITLE
Add current master builds of vsix files

### ISSUE THREAD

**Issue by brhx** [StarpTech/prettyhtml-vscode#2]
In order to drive adoption and live testing of this extension, I believe that builds from the `vsce package` commands should be built using a free CI and available to download and run easily for users.

(such as downloading [prettyhtml-vscode-0.0.1.vsix.zip](https://github.com/StarpTech/prettyhtml-vscode/files/2776893/prettyhtml-vscode-0.0.1.vsix.zip), the latest master build, unpacking, and then using `code --install-extension prettyhtml-vscode-0.0.1.vsix`).

I'm very happy to set this up, just wondering if this is something y'all would be interested in accepting a PR for!

**Comment by StarpTech** [comment]
Hi @sam3d that would be awesome. You could go with azure pipelines.
